apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jtq-frontend-replicaset
  namespace: jtq
  labels:
    app: jtq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jtq
  template:
    metadata:
      labels:
        app: jtq
    spec:
      containers:
      - name: jtq-frontend
        image: ghcr.io/jaumoso/jump-the-queue/jtq-frontend:latest
        ports:
        - containerPort: 4200
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jtq-nginx
  namespace: jtq
  labels:
    app: jtq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jtq
  template:
    metadata:
      labels:
        app: jtq
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:stable
        ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: jtq
  name: jtq-backend
  labels:
    app: jtq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jtq
  template:
    metadata:
      labels:
        app: jtq
    spec:
      containers:
      - name: jtq-backend
        image: ghcr.io/jaumoso/jump-the-queue/jtq-backend:latest
        ports:
        - containerPort: 8081