apiVersion: v1
kind: Service
metadata:
  name: jtq-frontend
spec:
  selector:
    app: jtq-frontend
    type: front-end
  ports:
  - port: 4200
    targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: jtq-backend
spec:
  selector:
    app: jtq-backend
    type: back-end
  ports:
  - port: 8081
    targetPort: 8081
